// Auto-generated by tools/gen_hash.rs — DO NOT EDIT
// Placeholder — will be overwritten during build with hash convergence

/// SHA256 hash of the code segment
pub const EXPECTED_FIRMWARE_HASH: [u8; 32] = [0u8; 32];

/// Schnorr signature of EXPECTED_FIRMWARE_HASH
pub const FIRMWARE_SIGNATURE: [u8; 64] = [0u8; 64];

/// Whether this build was signed with a developer key
pub const FIRMWARE_SIGNED: bool = false;

/// Exact code segment size
pub const FIRMWARE_SIZE: usize = 0;

/// Code segment address on instruction bus
pub const FIRMWARE_IADDR: u32 = 0x42060020;

/// Hash in hex format
pub const FIRMWARE_HASH_HEX: &str = "0000000000000000000000000000000000000000000000000000000000000000";
