// KasSigner — Air-gapped offline signing device for Kaspa
// Copyright (C) 2025-2026 KasSigner Project (kassigner@proton.me)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

// features/verify.rs — Firmware signature and hash verification
// 100% Rust, no-std, no libc
//
// Implements:
//   P0-1: Real read of mapped code segment + SHA256
//   P0-2: Constant-time hash comparison
//   P0-4: Redundant anti-glitch verification + flow counter
//
// ─── NOTE ON MEMORY MAP ────────────────────────────────────────────
//
// The ESP-IDF 2nd stage bootloader loads the app from flash and maps
// its segments into virtual memory:
//
//   Data segment:  flash offset 0x10020 → vaddr 0x3C00_0020 (data bus)
//   DRAM segment:   flash → vaddr 0x3FC8_xxxx (SRAM, initialized data)
//   Code segment: flash offset 0x20020 → vaddr 0x4201_0020 (instruction bus)
//
// The .bin file that espflash flashes contains headers + all segments
// packed sequentially. We cannot replicate the .bin hash by reading
// from mapped memory because the layout differs (segments are scattered
// across different buses).
//
// STRATEGY: gen_hash computes the hash of the full binary on the HOST.
// At runtime, we verify the mapped CODE segment (what the CPU
// will execute) matches a hash also computed over that segment.
//
// For full .bin verification, we would need raw access to the
// SPI flash bus (not memory-mapped). This will be implemented in Phase 2
// with a pure Rust SPI flash driver.
//
// FOR NOW: we use a pragmatic approach of verifying the code segment
// mapped in memory. This detects modifications to executable code,
// which is the most relevant attack vector.


use crate::log;
use sha2::{Sha256, Digest};
use core::sync::atomic::{compiler_fence, Ordering};

// Use centralized crypto module instead of local functions
use crate::crypto::{constant_time, flow};

// ─── Expected execution flow (M-11) ────────────────────────────────────
//
// The stage sequence a clean production verification produces, computed at
// compile time by `flow::expect`. This replaces the hand-written
// `2 + (4 * 2) = 10`: that arithmetic was correct only as long as nobody
// added, removed or reordered a `flow::step()`, and a stale total silently
// turns the anti-glitch check into an assertion that always fails or, worse,
// one that a compensating pair of glitches can satisfy. Written as the actual
// sequence, the constant tracks the code.
//
// Two passes of `do_verify_mapped_code`, each contributing four stages, after
// the two stages in `verify_firmware` itself.
#[cfg(feature = "production")]
const EXPECTED_FLOW: u32 = flow::expect(&[
    flow::TAG_VERIFY_START,
    flow::TAG_ANTI_ROLLBACK,
    // pass 1
    flow::TAG_PASS_START,
    flow::TAG_DATA_READ,
    flow::TAG_HASH,
    flow::TAG_COMPARE,
    // pass 2
    flow::TAG_PASS_START,
    flow::TAG_DATA_READ,
    flow::TAG_HASH,
    flow::TAG_COMPARE,
]);

// ─── Firmware hash (auto-generated by tools/gen_hash.rs) ───────────
//
// NOT gated on `silent`. It was, until 2026-08-02, which meant a `production`
// build had no FIRMWARE_HASH, no FIRMWARE_SIZE and no FIRMWARE_SIGNATURE, so
// the strict verification that `production` exists to enable could not compile.
include!("../firmware_hash.rs");

/// `FIRMWARE_SIGNED`, read in a way the optimiser cannot see through.
///
/// The constant is a `const bool` and it is read in two `if` conditions
/// below. In an UNSIGNED production build it is `false`, which makes the
/// production branch of `verify_firmware` provably return
/// `InvalidSignature` every time; the caller in `app/signing.rs` matches that
/// into an arm ending in `halt_forever`, which is `-> !`, and LTO then proves
/// the boot never reaches the wallet and deletes it. Measured 2026-08-26 on
/// the first 1.0.7 Docker build: every unsigned image collapsed to 244-271 kB
/// against 904-912 kB signed, with no BIP39 wordlist, no UI text and 47 kB
/// of code. The unsigned artifact exists so a verifier can rebuild it and
/// compare against the published hash; a stub makes that comparison prove
/// nothing about the firmware anyone runs.
///
/// A volatile read keeps the value truthful and the runtime behaviour
/// identical (an unsigned production image still halts at boot) while
/// denying the compiler the proof, so the whole firmware stays in both
/// images. It was `core::hint::black_box` until the first 1.0.7 release
/// build. `black_box` is documented as a hint with no guaranteed effect,
/// so an aggressive LTO pass is licensed to see through it and delete the
/// wallet again. `read_volatile` is a guarantee: the load must be
/// performed and cannot be constant-folded. The Docker build asserts the
/// property on every release (each unsigned app image full-sized and
/// within 64 KiB of its signed pair), so a compiler that ever defeats
/// this barrier fails the build instead of shipping a stub.
///
/// The only SOURCE inputs that differ between signed and unsigned are the
/// signature bytes, this flag, and the embedded hash; the compiled bytes
/// differ far more broadly (measured 2026-08-26: cmp -l counts ~623-630 k
/// differing bytes, first divergence at byte 289), because those constants
/// shift the compiler's output. Verification therefore compares unsigned
/// against unsigned, never a byte-diff of signed against unsigned.
///
/// The design that removes the need for this, hash/signature/flag in a
/// section the hash excludes, is recorded in STATE.md as a 1.1 item.
#[inline(always)]
fn firmware_signed() -> bool {
    // A `static` bound to the constant gives the read a stable address.
    static SIGNED: bool = FIRMWARE_SIGNED;
    // SAFETY: `&SIGNED` is a valid, aligned, initialised `bool` that lives
    // for the whole program and is never written. The volatile read exists
    // to deny the optimiser, not because the memory is special.
    unsafe { core::ptr::read_volatile(&SIGNED) }
}

// ─── ESP32-S3 memory map ─────────────────────────────────────
//
// The ESP32-S3 has SEPARATE buses for instructions and data:
//
//   Bus de instrucciones (IRAM/ICache): 0x4200_0000 — 0x43FF_FFFF
//     → Execute only. CANNOT read data with load instructions.
//
//   Data bus (DRAM/DCache):         0x3C00_0000 — 0x3DFF_FFFF
//     → Can read data normally. Same physical flash.
//
// The same flash is mapped on both buses. To READ the firmware
// contents (compute SHA256), we MUST use the data bus (0x3C...).
//
// Conversion: data_addr = iram_addr - 0x4200_0000 + 0x3C00_0000
//
// From the ESP-IDF bootloader log:
//   segment 0: paddr=00010020 vaddr=3c000020 size=05e84h  → data (rodata)
//   segment 4: paddr=00020020 vaddr=42010020 size=0af5ch  → code (text)
//
// The code segment is on the instruction bus (0x4201_0020),
// but we can read it as data from 0x3C01_0020.

/// Instruction bus base for mapped flash
const IRAM_FLASH_BASE: u32 = 0x4200_0000;

/// Data bus base for mapped flash
const DRAM_FLASH_BASE: u32 = 0x3C00_0000;

/// Code segment address on instruction bus — from gen_hash
const CODE_SEGMENT_IADDR: u32 = FIRMWARE_IADDR;

/// Equivalent address on data bus (for reading)
const CODE_SEGMENT_DADDR: u32 = CODE_SEGMENT_IADDR - IRAM_FLASH_BASE + DRAM_FLASH_BASE;

/// Maximum code segment size (1MB, more than enough)
pub const CODE_SEGMENT_MAX_SIZE: usize = 0x0010_0000;

// Exports for main.rs
/// Code segment start address on the instruction bus.
pub const FIRMWARE_START_ADDR: u32 = CODE_SEGMENT_IADDR;
/// Maximum allowed firmware size in bytes.
pub const FIRMWARE_MAX_SIZE: usize = CODE_SEGMENT_MAX_SIZE;

// ─── Magic values for anti-glitch ────────────────────────────────────

const CANARY_PRE_VERIFY: u32  = 0xDEAD_BEEF;
const CANARY_POST_VERIFY: u32 = 0xCAFE_BABE;

// Flow counter and constant_time now come from crate::crypto
// Stages per pass of do_verify_mapped_code:
//   +1 Start read
//   +1 Data read OK
//   +1 Hash computed
//   +1 Comparison completed
// Total per pass: 4
//
// Production (2 passes): 2 (prior) + 4 + 4 = 10
// Development (1 pass):  2 (prior) + 4     = 6

// ─── Public types ───────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq)]
/// Firmware verification outcome.
pub enum VerificationResult {
    Valid,
    InvalidHash,
    InvalidSignature,
    VersionTooOld,
    ReadError,
    FlowViolation,
    CanaryCorrupt,
}

/// Firmware metadata loaded from the embedded hash constants.
pub struct FirmwareInfo {
    pub version_major: u8,
    pub version_minor: u8,
    pub version_patch: u8,
    pub expected_hash: [u8; 32],
    /// Lowest version this image will accept for ITSELF. A build-configuration
    /// assertion, not anti-rollback.
    ///
    /// Both sides of the comparison come from this same image: the version from
    /// `crate::version`, the floor from the constant in `new()`. An older signed
    /// release carries its own consistent pair and boots normally, so nothing
    /// here prevents a downgrade and nothing could, since the check ships inside
    /// the code being replaced.
    ///
    /// Real rollback protection is the `SECURE_VERSION` eFuse, 16 bits used as a
    /// thermometer counter, so 16 increments for the life of a chip. Reaching it
    /// needs an ESP-IDF bootloader built with CONFIG_BOOTLOADER_APP_ANTI_ROLLBACK
    /// and an `esp_app_desc_t` in the image that a bare-metal Rust build does not
    /// emit, so it is a change of app format rather than a change here.
    ///
    /// Deliberately not done. Secure Boot already stops an unsigned or foreign
    /// build from running, the residual risk is only a legitimately signed older
    /// release being reflashed, and unsigned dev builds running on unburned
    /// hardware is intended: the source is public and a user loading whatever
    /// version they want on their own device is the design, not a gap.
    ///
    /// At 100 against a real version of 10005 this has never fired and cannot.
    pub min_version: u32,
}

impl FirmwareInfo {
    pub const fn new() -> Self {
        Self {
            version_major: crate::version::MAJOR,
            version_minor: crate::version::MINOR,
            version_patch: crate::version::PATCH,
            expected_hash: EXPECTED_FIRMWARE_HASH,
            min_version: 100,
        }
    }

    // ═══════════════════════════════════════════════════════════════
    // MAIN VERIFICATION
    // ═══════════════════════════════════════════════════════════════

        /// Verify firmware integrity: hash check + signature validation.
pub fn verify_firmware(
        &self,
        firmware_start: u32,
        max_size: usize,
    ) -> VerificationResult {
        flow::reset();

        // ── Stage 1: Start ─────────────────────────────────────
        flow::step(flow::TAG_VERIFY_START); // STAGE 1

        log!("   Verifying firmware...");
        log!("   Code segment: 0x{:08X}", firmware_start);

        let canary_pre = CANARY_PRE_VERIFY;
        compiler_fence(Ordering::SeqCst);

        // ── Stage 2: Version floor ──────────────────────────────
        let current_version = self.version_as_number();
        if current_version < self.min_version {
            log!("   FAIL: Version {} below floor {}", current_version, self.min_version);
            return VerificationResult::VersionTooOld;
        }
        log!("   Version {} >= floor {} OK", current_version, self.min_version);
        flow::step(flow::TAG_ANTI_ROLLBACK); // STAGE 2

        // ════════════════════════════════════════════════════════
        // DEVELOPMENT MODE
        // ════════════════════════════════════════════════════════
        #[cfg(not(feature = "production"))]
        {
            log!("   [DEV] Development mode");

            if constant_time::eq(&self.expected_hash, &[0u8; 32]) {
                log!("   [DEV] Hash not configured — skip");
                return VerificationResult::Valid;
            }

            // Real but non-blocking verification
            let dev_result = self.do_verify_mapped_code(firmware_start, max_size);

            compiler_fence(Ordering::SeqCst);
            if canary_pre != CANARY_PRE_VERIFY {
                log!("   [DEV] ALERT: Canary corrupt!");
                return VerificationResult::CanaryCorrupt;
            }

            match dev_result {
                VerificationResult::Valid => {
                    log!("   [DEV] Code segment hash: OK");
                }
                _ => {
                    log!("   [DEV] WARNING: Hash mismatch ({:?}), continuing", dev_result);
                }
            }

            // Developer signature check skipped in dev builds:
            // - Schnorr verify uses k256 point multiplication (~16KB stack)
            // - Combined with hardware init, this overflows the bare-metal stack
            // - Production builds run signature verification with stricter flow
            if firmware_signed() {
                log!("   [DEV] Signature present — skipped (dev mode, verified in production)");
            } else {
                log!("   [DEV] Build not signed");
            }

            VerificationResult::Valid
        }

        // ════════════════════════════════════════════════════════
        // PRODUCTION MODE — Double pass
        // ════════════════════════════════════════════════════════
        #[cfg(feature = "production")]
        {
            log!("   [PROD] STRICT verification");

            if constant_time::eq(&self.expected_hash, &[0u8; 32]) {
                log!("   CRITICAL: Hash not configured in production!");
                return VerificationResult::InvalidHash;
            }

            // First pass
            let result1 = self.do_verify_mapped_code(firmware_start, max_size);
            compiler_fence(Ordering::SeqCst);

            if canary_pre != CANARY_PRE_VERIFY {
                log!("   CRITICAL: Canary pre-verify corrupt!");
                return VerificationResult::CanaryCorrupt;
            }

            let canary_mid = CANARY_POST_VERIFY;
            compiler_fence(Ordering::SeqCst);

            // Second pass
            let result2 = self.do_verify_mapped_code(firmware_start, max_size);
            compiler_fence(Ordering::SeqCst);

            if canary_mid != CANARY_POST_VERIFY {
                log!("   CRITICAL: Canary mid-verify corrupt!");
                return VerificationResult::CanaryCorrupt;
            }

            // Triple barrier
            if !matches!(result1, VerificationResult::Valid) {
                log!("   FAIL: First pass: {:?}", result1);
                return result1;
            }
            if !matches!(result2, VerificationResult::Valid) {
                log!("   FAIL: Second pass: {:?}", result2);
                return result2;
            }
            if result1 != result2 {
                log!("   CRITICAL: Inconsistent results!");
                return VerificationResult::CanaryCorrupt;
            }

            // Flow accumulator: the tagged sequence declared in EXPECTED_FLOW.
            // `flow::verify` double-reads the accumulator; a single glitched
            // load cannot produce a pass.
            if !flow::verify(EXPECTED_FLOW) {
                log!(
                    "   CRITICAL: Flow 0x{:08X} != expected 0x{:08X}",
                    flow::count(),
                    EXPECTED_FLOW
                );
                return VerificationResult::FlowViolation;
            }

            log!("   Verified: double pass + anti-glitch OK");

            // Verify developer signature (MANDATORY in production)
            if !firmware_signed() {
                log!("   CRITICAL: Unsigned build in production mode!");
                return VerificationResult::InvalidSignature;
            }

            let sig_result = self.verify_signature();
            if !matches!(sig_result, VerificationResult::Valid) {
                log!("   CRITICAL: Developer signature INVALID!");
                return VerificationResult::InvalidSignature;
            }
            log!("   Developer signature: VALID");

            VerificationResult::Valid
        }
    }

    // ═══════════════════════════════════════════════════════════════
    // CODE SEGMENT VERIFICATION
    // ═══════════════════════════════════════════════════════════════
    //
    // The code segment is mapped on the instruction bus
    // (0x4201_0020), but we CANNOT read it as data from there —
    // the Xtensa has separate buses and gives LoadStoreError.
    //
    // The same flash is accessible on the data bus (0x3C01_0020).
    // Convert: data_addr = iram_addr - 0x4200_0000 + 0x3C00_0000
    //
    // We determine size by scanning until we find empty flash.

    fn do_verify_mapped_code(
        &self,
        code_start_iram: u32,
        max_size: usize,
    ) -> VerificationResult {
        flow::step(flow::TAG_PASS_START); // Stage: start

        // ── Convert IRAM address → DRAM ─────────────────────
        //
        // code_start_iram is on instruction bus (0x4201_0020)
        // We need the equivalent address on data bus (0x3C01_0020)
        let code_start = if (IRAM_FLASH_BASE..(IRAM_FLASH_BASE + 0x0200_0000)).contains(&code_start_iram)
        {
            code_start_iram - IRAM_FLASH_BASE + DRAM_FLASH_BASE
        } else if (DRAM_FLASH_BASE..(DRAM_FLASH_BASE + 0x0200_0000)).contains(&code_start_iram)
        {
            // Already a DRAM address, use directly
            code_start_iram
        } else {
            log!("   ERROR: 0x{:08X} is not a valid flash address!", code_start_iram);
            return VerificationResult::ReadError;
        };

        // ── Determine segment size ───────────────────────
        //
        // Use FIRMWARE_SIZE from firmware_hash.rs, which gen_hash extracted
        // from the segment header in the ESP-IDF .bin. This ensures we
        // hash exactly the same bytes that gen_hash hashed.
        //
        // If FIRMWARE_SIZE is not set (= 0 or > max_size),
        // fall back to scanning for 0xFF.

        let code_size: usize = if FIRMWARE_SIZE > 0 && FIRMWARE_SIZE <= max_size {
            log!("   Segment size: {} bytes ({} KB)", FIRMWARE_SIZE, FIRMWARE_SIZE / 1024);
            FIRMWARE_SIZE
        } else {
            // Fallback: scan for end of code
            log!("   FIRMWARE_SIZE not available, scanning...");
            let mut size: usize = 0;
            let mut consecutive_ff: u32 = 0;
            const FF_THRESHOLD: u32 = 16;
            let scan_limit = core::cmp::min(max_size, 0x0010_0000);

            let mut offset: usize = 0;
            while offset < scan_limit {
                let addr = code_start as usize + offset;
                let word = unsafe {
                    core::ptr::read_volatile(addr as *const u32)
                };

                if word == 0xFFFF_FFFF {
                    consecutive_ff += 1;
                    if consecutive_ff >= FF_THRESHOLD {
                        size = offset - ((FF_THRESHOLD as usize - 1) * 4);
                        break;
                    }
                } else {
                    consecutive_ff = 0;
                    size = offset + 4;
                }
                offset += 4;
            }

            if size == 0 {
                log!("   ERROR: Empty or unmapped segment");
                return VerificationResult::ReadError;
            }
            // Align to 4 bytes
            size = (size + 3) & !3;
            log!("   Scanned segment: {} bytes ({} KB)", size, size / 1024);
            size
        };

        flow::step(flow::TAG_DATA_READ); // Stage: data read

        // ── Sanity check ────────────────────────────────────────
        let data: &[u8] = unsafe {
            core::slice::from_raw_parts(code_start as *const u8, code_size)
        };

        // Verify not all zeros
        let mut all_00 = true;
        let check_len = core::cmp::min(256, data.len());
        for i in 0..check_len {
            let val = unsafe { core::ptr::read_volatile(&data[i] as *const u8) };
            if val != 0x00 { all_00 = false; break; }
        }
        if all_00 {
            log!("   Segment reads as zeros (DRAM mapping unavailable)");
            return VerificationResult::ReadError;
        }

        // ── Compute SHA256 ─────────────────────────────────────
        flow::step(flow::TAG_HASH); // Stage: hash

        let mut hasher = Sha256::new();
        const CHUNK_SIZE: usize = 4096;
        let mut off = 0;
        while off < code_size {
            let end = core::cmp::min(off + CHUNK_SIZE, code_size);
            hasher.update(&data[off..end]);
            off = end;
        }

        let computed_hash: [u8; 32] = hasher.finalize().into();

        log!("   Computed hash: {}...", self.hash_to_hex_short(&computed_hash).as_str());
        log!("   Expected hash: {}...", self.hash_to_hex_short(&self.expected_hash).as_str());

        // ── Compare in constant time ────────────────────────
        flow::step(flow::TAG_COMPARE); // Stage: comparison

        let hashes_match = constant_time::eq(&computed_hash, &self.expected_hash);
        compiler_fence(Ordering::SeqCst);

        if hashes_match {
            VerificationResult::Valid
        } else {
            log!("   FAIL: Hash does NOT match!");
            log!("   (Expected in dev if gen_hash hashes the full .bin)");
            log!("   (Mapped segment hash differs from file hash)");
            VerificationResult::InvalidHash
        }
    }

    // ═══════════════════════════════════════════════════════════════
    // DEVELOPER SIGNATURE VERIFICATION
    // ═══════════════════════════════════════════════════════════════
    //
    // Verifies that EXPECTED_FIRMWARE_HASH was signed by the developer
    // using the Schnorr private key corresponding to DEV_PUBKEY.
    // This proves the firmware binary was built by the developer,
    // not by an attacker who modified the code and recomputed the hash.

    fn verify_signature(&self) -> VerificationResult {
        // DEV_PUBKEY is in fw_update.rs
        let pubkey = &crate::features::fw_update::DEV_PUBKEY;

        // Check pubkey is not all zeros (placeholder)
        if constant_time::eq(pubkey, &[0u8; 32]) {
            log!("   WARNING: DEV_PUBKEY not configured (all zeros)");
            return VerificationResult::InvalidSignature;
        }

        let sig = crate::wallet::schnorr::SchnorrSignature { bytes: FIRMWARE_SIGNATURE };

        match crate::wallet::schnorr::schnorr_verify(pubkey, &self.expected_hash, &sig) {
            Ok(()) => VerificationResult::Valid,
            Err(_) => {
                log!("   Schnorr signature verification FAILED");
                VerificationResult::InvalidSignature
            }
        }
    }

    // ─── Utilities ──────────────────────────────────────────────
        /// Get the expected firmware hash for display.
pub fn get_display_hash(&self) -> [u8; 32] {
        self.expected_hash
    }
        /// Convert a 32-byte hash to a short hex prefix for user attestation,
    /// as `"xxxxxxxx xxxxxxxx"`: 8 bytes, grouped in fours.
    ///
    /// M-12: this was 4 bytes. A 32-bit firmware attestation is grindable in
    /// seconds to minutes on commodity hardware, so an attacker who can
    /// replace the firmware can also produce a build whose displayed token
    /// matches the one the user memorised. A token an adversary can collide
    /// is not an attestation. 64 bits is out of reach of that attack.
    ///
    /// Grouped in fours because the whole value of this string is a human
    /// comparing it against a value from elsewhere, and people compare
    /// 4-character groups reliably and 16-character runs badly. The space is
    /// display only and is not part of the hash.
    ///
    /// Width note: 17 characters, so callers slicing this for a fixed-width
    /// field must allow for that, not 8. Both `show_verification_screen`
    /// implementations were capping at 16 and are updated with it.
pub fn hash_to_hex_short(&self, hash: &[u8; 32]) -> heapless::String<24> {
        use core::fmt::Write;
        let mut s = heapless::String::new();
        for (i, byte) in hash[0..8].iter().enumerate() {
            if i == 4 {
                let _ = s.push(' ');
            }
            write!(&mut s, "{byte:02x}").unwrap_or(());
        }
        s
    }

        /// Format the firmware version as a "major.minor.patch" string.
pub fn version_string(&self) -> heapless::String<16> {
        use core::fmt::Write;
        let mut s = heapless::String::new();
        write!(
            &mut s,
            "{}.{}.{}",
            self.version_major, self.version_minor, self.version_patch
        )
        .unwrap_or(());
        s
    }

        /// Get the raw firmware version number.
pub fn version_as_number(&self) -> u32 {
        (self.version_major as u32) * 10000
            + (self.version_minor as u32) * 100
            + (self.version_patch as u32)
    }
}
