// KasSigner — Air-gapped offline signing device for Kaspa
// Copyright (C) 2025-2026 KasSigner Project (kassigner@proton.me)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

// KasSigner — Firmware Hash Generator
// 100% Rust
//
// Parses the ESP-IDF binary generated by espflash, finds the code segment
// (load_addr = 0x4201_0020), and computes its SHA256.
//
// The hash must match EXACTLY what the bootloader computes
// when reading the same region from the data bus (0x3C01_0020).
//
// ESP-IDF binary format:
//   [0x00]       u8   magic (0xE9)
//   [0x01]       u8   segment_count
//   [0x02-0x03]  u16  SPI mode/speed
//   [0x04-0x07]  u32  entry_point
//   [0x08-0x17]  ...  more header fields
//   [0x18]       start of extended header (16 bytes)
//   [0x28]       start of segments
//
//   Each segment:
//     [+0x00] u32 load_addr   (virtual address where it loads)
//     [+0x04] u32 data_size   (size of segment data)
//     [+0x08] u8[data_size]   segment data
//
// We look for the segment with load_addr in the range 0x4200_0000..0x43FF_FFFF
// (flash mapped on instruction bus = code segment).
//
// IMPORTANT: The bootloader does not read the full segment — it scans until
// finding 16 consecutive 0xFFFFFFFF words. We replicate that logic
// here to hash exactly the same bytes.

use sha2::{Sha256, Digest};
use std::fs;
use std::io::Write;
use std::path::Path;
use k256::{
    SecretKey,
    Scalar,
    ProjectivePoint,
    elliptic_curve::{
        sec1::ToEncodedPoint,
        ops::Reduce,
        ScalarPrimitive,
    },
};

/// Instruction bus range for flash-mapped memory on ESP32-S3
const IRAM_FLASH_BASE: u32 = 0x4200_0000;
const IRAM_FLASH_END: u32 = 0x4400_0000;

/// Header magic for ESP-IDF image format
const ESP_IMAGE_MAGIC: u8 = 0xE9;

/// Main header size: 24 bytes
/// Segments start immediately after (offset 0x18)
const ESP_IMAGE_HEADER_SIZE: usize = 24;
const SEGMENT_HEADER_SIZE: usize = 8;

/// Check `compute_challenge` against the BIP-340 specification.
///
/// Runs before anything is signed, and aborts if it fails.
///
/// This exists because the function it tests was wrong for the life of the
/// project (H-12): it computed a plain `SHA256(R.x || P.x || m)` instead of the
/// BIP-340 tagged hash, so every signature this tool produced was rejected by
/// the firmware and by any other verifier. Nothing caught it. The device had a
/// Schnorr known-answer test, but that test signs and verifies with the device's
/// own code, so an implementation that is wrong and self-consistent passes. This
/// tool had no test at all, and the only place the two met was behind
/// `--features production`, which did not compile.
///
/// So both sides are now anchored to the specification rather than to each
/// other: `wallet/schnorr.rs::test_bip340_published_vector` verifies the same
/// published vector on the device. Neither can drift without failing.
///
/// The values come from BIP-340 test vector 0, derived from first principles
/// rather than copied:
///   secret key 0x03, message all zeros, aux_rand all zeros
///   R.x    = first 32 bytes of the published signature
///   P.x    = F9308A01...BCE036F9
///   e      = tagged_hash("BIP0340/challenge", R.x || P.x || m) mod n
fn self_test_challenge() {
    const RX: [u8; 32] = [
        0xE9, 0x07, 0x83, 0x1F, 0x80, 0x84, 0x8D, 0x10,
        0x69, 0xA5, 0x37, 0x1B, 0x40, 0x24, 0x10, 0x36,
        0x4B, 0xDF, 0x1C, 0x5F, 0x83, 0x07, 0xB0, 0x08,
        0x4C, 0x55, 0xF1, 0xCE, 0x2D, 0xCA, 0x82, 0x15,
    ];
    const PX: [u8; 32] = [
        0xF9, 0x30, 0x8A, 0x01, 0x92, 0x58, 0xC3, 0x10,
        0x49, 0x34, 0x4F, 0x85, 0xF8, 0x9D, 0x52, 0x29,
        0xB5, 0x31, 0xC8, 0x45, 0x83, 0x6F, 0x99, 0xB0,
        0x86, 0x01, 0xF1, 0x13, 0xBC, 0xE0, 0x36, 0xF9,
    ];
    const MSG: [u8; 32] = [0u8; 32];
    const EXPECTED_E: [u8; 32] = [
        0x6B, 0xB6, 0xB9, 0x3A, 0x91, 0xF2, 0xEC, 0xC0,
        0xCD, 0x92, 0x4F, 0x4F, 0x9B, 0xAA, 0xBB, 0x5E,
        0x6E, 0xB2, 0x17, 0x45, 0xBB, 0x00, 0xF2, 0xCE,
        0xBD, 0xAA, 0xC9, 0x08, 0xBB, 0x5D, 0x86, 0xCE,
    ];

    let e = compute_challenge(&RX, &PX, &MSG);
    if scalar_to_bytes(&e) != EXPECTED_E {
        eprintln!("  FATAL: BIP-340 challenge self-test FAILED.");
        eprintln!("  compute_challenge does not match the specification, so any");
        eprintln!("  signature produced here would be rejected by the firmware.");
        eprintln!("  expected {}", hex(&EXPECTED_E));
        eprintln!("  got      {}", hex(&scalar_to_bytes(&e)));
        std::process::exit(2);
    }
}

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{:02x}", x)).collect()
}

fn main() {
    self_test_challenge();

    let args: Vec<String> = std::env::args().collect();

    if args.len() < 2 || args.len() > 3 {
        eprintln!("Usage: gen-hash <firmware-binary> [signing-key-path]");
        eprintln!("  firmware-binary: .bin file from espflash save-image");
        eprintln!("  signing-key-path: optional path to dev_signing_key.bin");
        eprintln!("  If no key is provided, signature will be all zeros (unsigned).");
        std::process::exit(1);
    }

    let firmware_path = &args[1];

    println!("  Firmware Segment Hash Generator");
    println!("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");

    // ── Read the binary ─────────────────────────────────────────
    let firmware_data = match fs::read(firmware_path) {
        Ok(data) => data,
        Err(e) => {
            eprintln!("  Error leyendo firmware: {}", e);
            std::process::exit(1);
        }
    };

    println!("  File: {}", firmware_path);
    println!("  Total size: {} bytes ({} KB)", firmware_data.len(), firmware_data.len() / 1024);

    // ── Detect format ────────────────────────────────────────
    // Si es un ELF (empieza con 0x7F 'E' 'L' 'F'), necesitamos
    // convertirlo primero con espflash. Pero normalmente el build
    // script pasa el ELF y espflash lo convierte internamente.
    //
    // In our case, espflash flash generates a temporary .bin.
    // Pero nosotros recibimos el ELF. Necesitamos parsearlo como
    // ESP-IDF image — que es lo que espflash realmente flashea.
    //
    // SOLUTION: We use `espflash save-image` to generate the .bin,
    // o parseamos el ELF directamente buscando las secciones.
    //
    // For simplicity, first try to parse as ESP-IDF image.
    // If that fails (it is an ELF), try to parse ELF sections.

    let signing_key_path: Option<String> = if args.len() >= 3 { Some(args[2].clone()) } else { None };

    if firmware_data.len() < ESP_IMAGE_HEADER_SIZE + SEGMENT_HEADER_SIZE {
        eprintln!("  File too small to be a valid firmware");
        std::process::exit(1);
    }

    if firmware_data[0] == ESP_IMAGE_MAGIC {
        process_esp_image(&firmware_data, signing_key_path.as_deref());
    } else if &firmware_data[0..4] == b"\x7fELF" {
        process_elf(&firmware_data, signing_key_path.as_deref());
    } else {
        eprintln!("  Unrecognized format. Expected ESP-IDF image (0xE9) or ELF.");
        eprintln!("  First byte: 0x{:02X}", firmware_data[0]);
        eprintln!();
        eprintln!("  If passing an ELF, generate .bin first:");
        eprintln!("    espflash save-image --chip esp32s3 <ELF> firmware.bin");
        eprintln!("    gen-hash firmware.bin");
        std::process::exit(1);
    }
}

// ─── Parser de ESP-IDF image format ───────────────────────────────────

fn process_esp_image(data: &[u8], signing_key: Option<&str>) {
    println!("  Format: ESP-IDF image");

    let segment_count = data[1] as usize;
    println!("  Segments: {}", segment_count);

    // Entry point
    let entry = u32::from_le_bytes([data[4], data[5], data[6], data[7]]);
    println!("  Entry point: 0x{:08X}", entry);

    // Iterate over segments
    let mut offset = ESP_IMAGE_HEADER_SIZE;
    let mut code_segment: Option<(usize, usize, u32)> = None; // (data_offset, size, load_addr)

    for i in 0..segment_count {
        if offset + SEGMENT_HEADER_SIZE > data.len() {
            eprintln!("  Segment {} truncated (offset {} > len {})", i, offset, data.len());
            break;
        }

        let load_addr = u32::from_le_bytes([
            data[offset], data[offset + 1], data[offset + 2], data[offset + 3],
        ]);
        let seg_size = u32::from_le_bytes([
            data[offset + 4], data[offset + 5], data[offset + 6], data[offset + 7],
        ]) as usize;

        let data_offset = offset + SEGMENT_HEADER_SIZE;

        println!("  Segment {}: load=0x{:08X}  size=0x{:05X} ({:6} bytes) {}",
            i, load_addr, seg_size, seg_size,
            if load_addr >= IRAM_FLASH_BASE && load_addr < IRAM_FLASH_END {
                " ← CODE (IRAM)"
            } else {
                ""
            }
        );

        // Find the code segment (mapped on instruction bus)
        if load_addr >= IRAM_FLASH_BASE && load_addr < IRAM_FLASH_END {
            if code_segment.is_some() {
                println!("  WARN: Multiple code segments. Using the last one.");
            }
            code_segment = Some((data_offset, seg_size, load_addr));
        }

        offset = data_offset + seg_size;
    }

    // ── Hash the code segment ───────────────────────────
    match code_segment {
        Some((data_offset, seg_size, load_addr)) => {
            hash_code_segment(data, data_offset, seg_size, load_addr, signing_key);
        }
        None => {
            eprintln!("  Code segment not found (IRAM 0x4200_0000+)!");
            eprintln!("  Available segments do not include flash-mapped code.");
            std::process::exit(1);
        }
    }
}

// ─── Parser de ELF (fallback) ─────────────────────────────────────────
//
// Xtensa ESP32-S3 binaries are ELF32 little-endian.
// Find the section with virtual address in the IRAM flash range.

fn process_elf(data: &[u8], signing_key: Option<&str>) {
    println!("  Format: ELF");

    // ELF32 header parsing (minimal)
    if data.len() < 52 {
        eprintln!("  ELF too small");
        std::process::exit(1);
    }

    // e_phoff: offset de la program header table
    let ph_offset = u32::from_le_bytes([data[28], data[29], data[30], data[31]]) as usize;
    // e_phentsize: size of each program header entry
    let ph_entry_size = u16::from_le_bytes([data[42], data[43]]) as usize;
    // e_phnum: number of program header entries
    let ph_num = u16::from_le_bytes([data[44], data[45]]) as usize;

    println!("  Program headers: {} entries @ offset 0x{:X}", ph_num, ph_offset);

    let mut code_segment: Option<(usize, usize, u32)> = None;

    for i in 0..ph_num {
        let off = ph_offset + i * ph_entry_size;
        if off + 32 > data.len() {
            break;
        }

        let p_type = u32::from_le_bytes([data[off], data[off+1], data[off+2], data[off+3]]);
        let p_offset = u32::from_le_bytes([data[off+4], data[off+5], data[off+6], data[off+7]]) as usize;
        let p_vaddr = u32::from_le_bytes([data[off+8], data[off+9], data[off+10], data[off+11]]);
        let p_filesz = u32::from_le_bytes([data[off+16], data[off+17], data[off+18], data[off+19]]) as usize;

        // PT_LOAD = 1
        if p_type == 1 {
            println!("  LOAD {}: vaddr=0x{:08X}  filesz=0x{:05X} ({:6} bytes) {}",
                i, p_vaddr, p_filesz, p_filesz,
                if p_vaddr >= IRAM_FLASH_BASE && p_vaddr < IRAM_FLASH_END {
                    " ← CODE"
                } else {
                    ""
                }
            );

            if p_vaddr >= IRAM_FLASH_BASE && p_vaddr < IRAM_FLASH_END {
                code_segment = Some((p_offset, p_filesz, p_vaddr));
            }
        }
    }

    match code_segment {
        Some((data_offset, seg_size, load_addr)) => {
            hash_code_segment(data, data_offset, seg_size, load_addr, signing_key);
        }
        None => {
            eprintln!("  No LOAD segment found with vaddr in IRAM flash range.");
            eprintln!("  Try generating a .bin first:");
            eprintln!("    espflash save-image --chip esp32s3 <ELF> firmware.bin");
            std::process::exit(1);
        }
    }
}

// ─── Code segment hash ──────────────────────────────────────
//
// Hashes exactly seg_size bytes from the code segment.
// The bootloader will use FIRMWARE_SIZE (= seg_size) to read the same
// cantidad de bytes desde DRAM y calcular el mismo hash.

fn hash_code_segment(file_data: &[u8], data_offset: usize, seg_size: usize, load_addr: u32, signing_key: Option<&str>) {
    println!();
    println!("  Hashing code segment:");
    println!("    Load addr:    0x{:08X}", load_addr);
    println!("    File offset:  0x{:05X}", data_offset);
    println!("    Segment size: {} bytes ({} KB)", seg_size, seg_size / 1024);

    if data_offset + seg_size > file_data.len() {
        eprintln!("  ERROR: Segment exceeds file size!");
        std::process::exit(1);
    }

    if seg_size == 0 {
        eprintln!("  ERROR: Zero-size segment!");
        std::process::exit(1);
    }

    let segment_data = &file_data[data_offset..data_offset + seg_size];

    // ── Calcular SHA256 ─────────────────────────────────────────
    let mut hasher = Sha256::new();
    hasher.update(segment_data);
    let hash = hasher.finalize();

    let hash_bytes: [u8; 32] = hash.clone().into();
    let hash_hex: String = hash.iter().map(|b| format!("{:02x}", b)).collect();
    let hash_short: String = hash.iter().take(4).map(|b| format!("{:02x}", b)).collect();

    println!();
    println!("  SHA256: {}", hash_hex);
    println!("  Short:  {}...", hash_short);

    // ── Sign the hash with developer key (if provided) ─────────
    let mut sig_bytes = [0u8; 64];
    let mut signed = false;

    if let Some(key_path) = signing_key {
        let key_data = match fs::read(key_path) {
            Ok(d) => d,
            Err(e) => {
                eprintln!("  ERROR reading signing key {}: {}", key_path, e);
                std::process::exit(1);
            }
        };
        if key_data.len() != 32 {
            eprintln!("  ERROR: Signing key must be exactly 32 bytes, got {}", key_data.len());
            std::process::exit(1);
        }

        let mut privkey = [0u8; 32];
        privkey.copy_from_slice(&key_data);

        match schnorr_sign(&privkey, &hash_bytes) {
            Ok(sig) => {
                sig_bytes = sig;
                signed = true;
                let sig_hex: String = sig_bytes.iter().take(8).map(|b| format!("{:02x}", b)).collect();
                println!("  Signature: {}... (signed)", sig_hex);
            }
            Err(e) => {
                eprintln!("  ERROR signing hash: {}", e);
                std::process::exit(1);
            }
        }

        // Zeroize private key from memory
        for b in privkey.iter_mut() { *b = 0; }
    } else {
        println!("  Signature: (none — no signing key provided)");
    }

    // ── Generate firmware_hash.rs ────────────────────────────────
    let hash_array: String = hash.iter()
        .map(|b| format!("0x{:02x}", b))
        .collect::<Vec<_>>()
        .join(", ");

    let sig_array: String = sig_bytes.iter()
        .map(|b| format!("0x{:02x}", b))
        .collect::<Vec<_>>()
        .join(", ");

    let output_path = Path::new("bootloader/src/firmware_hash.rs");
    let rust_code = format!(
r#"// Auto-generated by tools/gen_hash.rs — DO NOT EDIT
//
// Code segment hash + developer signature
// IRAM 0x{load_addr:08X}, DRAM 0x{dram_addr:08X}
// Segment size: {seg_size} bytes
// Signed: {signed}

/// SHA256 hash of the code segment
pub const EXPECTED_FIRMWARE_HASH: [u8; 32] = [
    {hash_array}
];

/// Schnorr signature of EXPECTED_FIRMWARE_HASH (signed by developer key)
/// All zeros if unsigned (development build without key)
pub const FIRMWARE_SIGNATURE: [u8; 64] = [
    {sig_array}
];

/// Whether this build was signed with a developer key
pub const FIRMWARE_SIGNED: bool = true;

/// Exact code segment size (from ESP-IDF binary header)
pub const FIRMWARE_SIZE: usize = {seg_size};

/// Code segment address on instruction bus (IRAM)
pub const FIRMWARE_IADDR: u32 = 0x{load_addr:08X};

/// Hash in hex format (for reference)
pub const FIRMWARE_HASH_HEX: &str = "{hash_hex}";
"#,
        load_addr = load_addr,
        seg_size = seg_size,
        dram_addr = load_addr - 0x4200_0000 + 0x3C00_0000,
        hash_array = hash_array,
        sig_array = sig_array,
        signed = signed,
        hash_hex = hash_hex,
    );

    let mut file = match fs::File::create(output_path) {
        Ok(f) => f,
        Err(e) => {
            eprintln!("  Error creating {}: {}", output_path.display(), e);
            std::process::exit(1);
        }
    };

    if let Err(e) = file.write_all(rust_code.as_bytes()) {
        eprintln!("  Error writing: {}", e);
        std::process::exit(1);
    }

    println!();
    println!("  Saved to: {}", output_path.display());
    if signed {
        println!("  Status: SIGNED (production-ready)");
    } else {
        println!("  Status: UNSIGNED (development build)");
    }
    println!("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
}

// ─── Schnorr signing (BIP340-compatible, secp256k1) ─────────────────

fn schnorr_sign(privkey: &[u8; 32], message: &[u8; 32]) -> Result<[u8; 64], String> {
    let sk = SecretKey::from_slice(privkey)
        .map_err(|e| format!("Invalid private key: {}", e))?;

    let d_scalar: Scalar = (*sk.to_nonzero_scalar()).into();

    let pubkey_point = ProjectivePoint::GENERATOR * d_scalar;
    let pubkey_affine = pubkey_point.to_affine();

    // BIP340: negate d if Y is odd
    let d = if has_even_y(&pubkey_affine) { d_scalar } else { d_scalar.negate() };

    let px = x_bytes(&pubkey_affine);

    // RFC6979 deterministic nonce
    let k_scalar = generate_rfc6979_nonce(privkey, message)?;

    let r_point = (ProjectivePoint::GENERATOR * k_scalar).to_affine();
    let k = if has_even_y(&r_point) { k_scalar } else { k_scalar.negate() };
    let rx = x_bytes(&r_point);

    // e = SHA256(R.x || P.x || message) mod n
    let e = compute_challenge(&rx, &px, message);

    // s = k + e * d (mod n)
    let s = k + (e * d);

    let mut sig = [0u8; 64];
    sig[..32].copy_from_slice(&rx);
    sig[32..].copy_from_slice(&scalar_to_bytes(&s));
    Ok(sig)
}

fn has_even_y(point: &k256::AffinePoint) -> bool {
    let encoded = point.to_encoded_point(false);
    let y_bytes = encoded.y().expect("not identity");
    y_bytes[31] & 1 == 0
}

fn x_bytes(point: &k256::AffinePoint) -> [u8; 32] {
    let encoded = point.to_encoded_point(true);
    let mut x = [0u8; 32];
    x.copy_from_slice(&encoded.as_bytes()[1..33]);
    x
}

fn scalar_to_bytes(s: &Scalar) -> [u8; 32] {
    let primitive: ScalarPrimitive<k256::Secp256k1> = (*s).into();
    primitive.to_bytes().into()
}

fn generate_rfc6979_nonce(privkey: &[u8; 32], message: &[u8; 32]) -> Result<Scalar, String> {
    use sha2::{Sha256, Digest};

    // HMAC-SHA256 based nonce: k = HMAC(privkey, SHA256(privkey || message))
    let mut seed_hasher = Sha256::new();
    seed_hasher.update(privkey);
    seed_hasher.update(message);
    let seed = seed_hasher.finalize();

    // Simple HMAC: H(key XOR opad || H(key XOR ipad || message))
    let mut ipad = [0x36u8; 64];
    let mut opad = [0x5cu8; 64];
    for i in 0..32 {
        ipad[i] ^= seed[i];
        opad[i] ^= seed[i];
    }

    let mut inner = Sha256::new();
    inner.update(&ipad);
    inner.update(message);
    let inner_hash = inner.finalize();

    let mut outer = Sha256::new();
    outer.update(&opad);
    outer.update(&inner_hash);
    let k_bytes: [u8; 32] = outer.finalize().into();

    let k_uint = k256::U256::from_be_slice(&k_bytes);
    let k_scalar = <Scalar as Reduce<k256::U256>>::reduce(k_uint);

    if k_scalar.is_zero().into() {
        return Err("Zero nonce generated".to_string());
    }
    Ok(k_scalar)
}

/// BIP-340 challenge: e = tagged_hash("BIP0340/challenge", R.x || P.x || m) mod n
///
/// The tag prefix was missing until 2026-08-02. This function computed a plain
/// `SHA256(R.x || P.x || m)`, while the device verifier in
/// `bootloader/src/wallet/schnorr.rs:241` computes the BIP-340 tagged hash,
/// `SHA256(SHA256(tag) || SHA256(tag) || R.x || P.x || m)`.
///
/// The two therefore disagreed on the challenge, so every signature this tool
/// produced was rejected by the firmware, and by any other BIP-340 verifier.
/// It went unnoticed because `--features production` never compiled, and the
/// development path skips the signature check entirely. Confirmed on hardware:
/// a signed production build halted with "Signature invalid".
///
/// The device is the correct side. This is the fix.
///
/// Consequence: every signed release from 1.0.0 through 1.0.4 carries a
/// signature that cannot verify. Re-signing those artifacts is the only way to
/// make their signatures meaningful.
fn compute_challenge(rx: &[u8; 32], px: &[u8; 32], message: &[u8; 32]) -> Scalar {
    use sha2::{Sha256, Digest};

    // SHA256("BIP0340/challenge"), verified independently.
    const TAG_HASH: [u8; 32] = [
        0x7b, 0xb5, 0x2d, 0x7a, 0x9f, 0xef, 0x58, 0x32,
        0x3e, 0xb1, 0xbf, 0x7a, 0x40, 0x7d, 0xb3, 0x82,
        0xd2, 0xf3, 0xf2, 0xd8, 0x1b, 0xb1, 0x22, 0x4f,
        0x49, 0xfe, 0x51, 0x8f, 0x6d, 0x48, 0xd3, 0x7c,
    ];

    let mut hasher = Sha256::new();
    hasher.update(TAG_HASH);
    hasher.update(TAG_HASH);
    hasher.update(rx);
    hasher.update(px);
    hasher.update(message);
    let e_bytes: [u8; 32] = hasher.finalize().into();
    let e_uint = k256::U256::from_be_slice(&e_bytes);
    <Scalar as Reduce<k256::U256>>::reduce(e_uint)
}
